### PR TITLE
More cleanup

### PR DESCRIPTION
**Pull request by dodexahedron**
This is almost entirely cleanup.
The only potentially externally-visible change in this set is the fact that I got rid of a custom exception class which really wasn't adding anything of value.
I also stole the auto-version text template from the essentials plugin and put it in here, so the versioning will be handled automatically for the revision number.

### CODE REVIEW

**Comment by dodexahedron** [comment]
Just some more cleanup and documentation.

**Comment by dodexahedron** [comment]
Going to clean up the BatteryBlockEntity and CockpitEntity classes, next.

**Comment by rogeriocamorim** [comment]
how can i get your SEServerExtender.exe?

**Comment by dodexahedron** [comment]
Now for a little work on ServerNetworkManager.
I'll post a build of this after I'm done.

**Comment by dodexahedron** [comment]
Now some work on LandingGearEntity

**Comment by dodexahedron** [comment]
Alright.  I'm done for tonight.
I'm going to release version 0.3.1.31 in binary form on my fork.

**Comment by dodexahedron** [comment]
Merged most recent changes

**Comment by dodexahedron** [comment]
Binaries can be downloaded at https://github.com/dodexahedron/SE-Community-Mod-API/releases/tag/v0.3.1.31-alpha

**Comment by dodexahedron** [comment]
My most recent commit, which will be pushed shortly, changes the version numbers dramatically.  Why?  Right now, it's impossible to know which version of SESE works with which version of SE.
The new versioning I put in uses the version number from SE as the first three numbers, and then has its own revision number at the end to differentiate each build.

For example, this week's patch build of SE is 1.68.6, so SESE would be 1.68.6.35, since 35 was the next build number.
Any SESE version 1.68.6.* would be compatible with SE 1.68.6, with limited or no compatibility with other versions of SE.

Unless someone comes up with a better idea, I'm going to keep that up for the future.

**Comment by joshuataylor** [comment]
:+1:

**Comment by dodexahedron** [comment]
Also, can these please get pulled (here and Essentials)?  It's getting to be quite the pile of files to re-merge the same way every single time,

**Comment by dodexahedron** [comment]
Version 1.68.6.45 will be released in binary form shortly on my fork.

**Comment by dodexahedron** [comment]
Get it here:
https://github.com/dodexahedron/SE-Community-Mod-API/releases/tag/v1.68.6.45-alpha

**Comment by dodexahedron** [comment]
Binary release of updated version available here:
https://github.com/dodexahedron/SE-Community-Mod-API/releases/tag/v1.68.8.47-alpha

**Comment by dodexahedron** [comment]
I've added a minor (**but extremely useful**) feature.  SESE now has a button to repair a CubeGrid or CubeGridBlock, which sets buildpercent and integritypercent to 1 on the selected entity (in the case of a block) or all child entities (in the case of a grid).
Binary release is available on my fork.

**Comment by Devlah** [comment]
Decided to test this out on my server.  It doesn't seem to be able to load the plugins (Essentials and SEMOTD).

**Comment by McyD** [comment]
Had the same issue yesterday, seems plugins have to be updated to work.  As Tyrsis's essentials does not load, but dodexahedron's does.

**Comment by Devlah** [comment]
I REALLY like the idea of this function, so I hope a merge is coming.  Also, the version naming convention makes sense as well.

**Comment by dodexahedron** [comment]
@McyD @Devlah yes, if you use my fork, you have to use my fork of Essentials, as well, as there are breaking changes in the underlying code.

**Comment by dodexahedron** [comment]
This is really going to start diverging a lot faster, now, since I'm working on new features at this point. Are you planning to merge this or should I just keep doing what I'm doing independently?

**Comment by dodexahedron** [comment]
Ok I rebased this at your last commit and squashed some of the commits, so you have a lot less to look at if you want to analyze each commit.

**Pull request closed without merging**
