### PR TITLE
Code cleanup and making the build system-agnostic

### PR DESCRIPTION
**Pull request by dodexahedron**
This group of changes contains no functional changes to the libraries - changes to the libraries are entirely composed of code cleanup, minor reorganization (splitting classes into their own files), some minor memory optimization, and making the build work out of the box (it had a hard-coded output folder that likely won't exist on anyone else's machine).

I intend to continue these changes through the rest of the projects, but wanted to put a pull request in before significant work gets done on these files and a merge becomes more difficult.

Changes to SEServerExtender itself are mostly cleanup and optimization, as well, but also include a fix to selection behavior in the tree view after deleting an item.

### CODE REVIEW

**Comment by Tyrsis** [comment]
I had a bunch of backlogged changes I did.  Can you merge and then do another pull request?

**Comment by dodexahedron** [comment]
Sure. Give me a bit.

**Comment by dodexahedron** [comment]
Merged.
Version numbers bumped.
Tested this out on my server and it seems to work fine.
Will do the same to Essentials.

**Comment by Tyrsis** [comment]
Your changes seem to have upset some people, heh.  I reviewed the changes, and they didn't seem too bad.  One thing I was sort of was torn about was to change the whole m_ to _.  I left your changes though, as most of the stuff I've done in the past actually used _ like you've done instead of m_.  One thing I just _never_ do is space my parenthesis though.  I've seen different software houses do it either way, but I probably won't continue this trend, and it may be better just to not auto fix these.  The changes from m_ to _ are fine, but upset someone else strangely.  It is weird that after months, not a single person offers help, then suddenly someone does some changes and people get upset.

**Comment by dodexahedron** [comment]
Yeah feel free to do what you want on spacing.  Visual studio makes that so trivial that I honestly don't care. If you really want to export your spacing settings, though, I'll import them for this project so mine end up the same.  I just figure that whitespace can be ignored in diffs, so there's no real reason to bother upsetting people's local preferences for that.

**Pull request merged**
